name: penyimpanan_data_lokal
description: "Flutter project untuk Tugas 3 - SharedPreferences"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # Package untuk HTTP (kalau dipakai di tugas lain)
  http: ^0.13.6

  # Provider (kalau dipakai di tugas lain)
  provider: ^6.0.5

  # Tambahkan SharedPreferences untuk penyimpanan lokal
  shared_preferences: ^2.2.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
